SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `mousemove` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` CHAR(8) NOT NULL,
  `view_session_id` CHAR(36) NOT NULL,
  `event_sequence` INT UNSIGNED NOT NULL,
  `event_type` VARCHAR(40) NOT NULL,
  `UID` INT NOT NULL,
  `WID` INT NOT NULL,
  `attempt` INT NOT NULL,
  `test_id` INT NOT NULL,
  `correctness` TINYINT DEFAULT NULL,
  `self_reported_understand` TINYINT DEFAULT NULL,
  `estimated_understand` TINYINT DEFAULT NULL,
  `event_elapsed_ms` BIGINT UNSIGNED NOT NULL,
  `visible_delta_ms` BIGINT UNSIGNED NOT NULL,
  `total_visible_ms` BIGINT UNSIGNED NOT NULL,
  `play_count_since_reset` INT UNSIGNED NOT NULL DEFAULT 0,
  `pause_count_since_reset` INT UNSIGNED NOT NULL DEFAULT 0,
  `replay_count_since_reset` INT UNSIGNED NOT NULL DEFAULT 0,
  `reset_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `playback_position_ms` BIGINT UNSIGNED DEFAULT NULL,
  `speed_multiplier` DECIMAL(4,1) DEFAULT NULL,
  `playback_run_no` INT UNSIGNED NOT NULL DEFAULT 0,
  `selected_target_type` ENUM('all', 'word', 'group') DEFAULT NULL,
  `selected_words` JSON DEFAULT NULL,
  `selected_occurrence` INT UNSIGNED DEFAULT NULL,
  `skip_target_ms` BIGINT UNSIGNED DEFAULT NULL,
  `requested_play_ms` BIGINT UNSIGNED DEFAULT NULL,
  `play_to_end` TINYINT(1) DEFAULT NULL,
  `played_timeline_ms` BIGINT UNSIGNED DEFAULT NULL,
  `played_visible_wall_ms` BIGINT UNSIGNED DEFAULT NULL,
  `playback_end_reason` VARCHAR(40) DEFAULT NULL,
  `seek_from_ms` BIGINT UNSIGNED DEFAULT NULL,
  `seek_to_ms` BIGINT UNSIGNED DEFAULT NULL,
  `seek_delta_ms` BIGINT DEFAULT NULL,
  `seek_colored_intervals` JSON DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_mousemove_view_event` (`view_session_id`, `event_sequence`),
  KEY `idx_mousemove_teacher_created` (`teacher_id`, `created_at`),
  KEY `idx_mousemove_attempt_created` (`UID`, `WID`, `attempt`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
